### PR TITLE
Patch release to expose php node-types.json

### PR DESCRIPTION
**Pull request by aymannadeem**
Fixes https://github.com/github/semantic/pull/468 

Experiencing [a CI failure in Semantic](https://github.com/github/semantic/pull/468/checks?check_run_id=439636879) currently resulting from the `data-files` not exposing the `node-type.json` file required. 

This is a patch to fix that and release v0.3.0.1 for `tree-sitter-php`

### CODE REVIEW

**Comment by aymannadeem** [comment]
Once this is merged, we should see some errors over in https://github.com/github/semantic/pull/468 disappear. The PHP `node-types.json` was not being picked up by the call to `getNodeTypes` in Semantic. This had to be exposed in `data-files`, followed by a hackage release dance.

**Review by joshvera — APPROVED** [review]

**Comment by maxbrunsfeld** [comment]
I remember we were holding off for a while on bumping the PHP parser in semantic because of some big changes to the grammar that might require a lot of changes in assignment. Not sure if that is still anything to be concerned about.

**Comment by tclem** [comment]
We just need to do the assignment fixes in semantic if we're going to update tree-sitter-php (which is a little bit of sunk cost effort since assignment is going away).

**Comment by aymannadeem** [comment]
@tclem I was trying to fix Assignment errors I'm seeing in my other branch on Semantic. Agreed it's not ideal but I wasn't sure if it was okay to jump the gun and deprecate PHP Assignment just yet. I wanted to be more incremental while fixing those CI errors I'm seeing.

**Pull request merged**
