### PR TITLE
Update tree-sitter-ocaml

### PR DESCRIPTION
**Pull request by XVilka**
One more step towards https://github.com/github/semantic/issues/138

It includes the following updates in OCaml parser (to support modern syntax):
- https://github.com/tree-sitter/tree-sitter-ocaml/pull/36
- https://github.com/tree-sitter/tree-sitter-ocaml/pull/38

cc @314eter

### CODE REVIEW

**Comment by XVilka** [comment]
Failure is spurious is seems a GitHub fault, thus unrelated:
image

**Comment by smorimoto** [comment]
Can anyone check this?

**Comment by XVilka** [comment]
Ping?

**Comment by smorimoto** [comment]
@robrix

**Comment by XVilka** [comment]
Any news? This blocks https://github.com/github/semantic/issues/138

**Comment by XVilka** [comment]
Ping?

**Comment by smorimoto** [comment]
@tclem @patrickt @rewinfrey @maxbrunsfeld

**Comment by 314eter** [comment]
There are some big changes coming in tree-sitter/tree-sitter-ocaml#41.

I'm not sure it's necessary to keep this up to date with every change in tree-sitter-ocaml until someone is actively working on semantic support.

**Comment by 314eter** [comment]
There are some other problems that need to be solved before tree-sitter-ocaml is usable in semantic (see #290).

**Comment by XVilka** [comment]
Irrelevant now, @314eter is working on this anyway.

**Comment by 314eter** [comment]
I was working on it until https://github.com/github/semantic/pull/623#issuecomment-689009894 got me started on tree-sitter queries first, which is done now.

The tree-sitter-ocaml grammar will probably stay unchanged for the near future, so it can be updated in haskell-tree-sitter now, but only after #291 is merged (or rejected).

**Pull request closed without merging**
