### PR TITLE
Add tree-sitter-nix

### PR DESCRIPTION
**Pull request by roberth**
I wasn't sure what to put in the author fields and such when I initially made this module out-of-tree. Considering that no creative work was involved with this PR, feel free to put something more useful in those fields that isn't me.

### CODE REVIEW

**Comment by roberth** [comment]
I think I'll put your names on it, because I don't think I'll be maintaining it and it isn't "creative work". Will update PR after https://github.com/tree-sitter/haskell-tree-sitter/pull/112#issuecomment-498410287

**Comment by robrix** [comment]
I’m not sure what’s going on with `getUnboxedSumName` in the CI output here, but if this persists after you update the PR per the changes from #112, I’ll take a closer look 👍

Thanks very much for the PR!

**Comment by roberth** [comment]
I heard you like grammars, so I put some grammars inside your grammar! :sunglasses: 

This builds on my machine, so hoping for the best.

It's a shame that the `Grammar` type doesn't show up in the haddocks. Not sure if that's normal :man_shrugging:

**Comment by domenkozar** [comment]
Anything left to do to merge this one? I might work on https://github.com/hercules-ci/canonix/ at ZuriHac this weekend so would be nice to have this in :)

**Comment by robrix** [comment]
@domenkozar: I was just waiting on CI. Everything’s good!

**Comment by robrix** [comment]
Thanks very much @roberth!

**Pull request merged**
