### PR TITLE
Remove pointer-only constructors (#146).

### PR DESCRIPTION
**Pull request by patrickt**
We didn't export these constructors anyway, so there is no effect on
compatibility here.

### CODE REVIEW

**Comment by robrix** [comment]
`Tree` is another in the same vein.

**Comment by patrickt** [comment]
Addressed in #187.

**Comment by robrix** [comment]
Ooh we never merged this. We should merge this!

**Comment by patrickt** [comment]
Oh yeah I guess it has the fix for Tree in it, doesn’t it. Forgot!

**Pull request merged**
