### PR TITLE
Add OCaml support

### PR DESCRIPTION
**Pull request by XVilka**
Initial support for https://github.com/github/semantic/issues/138

I based it on the current Rust support in both Tree-sitter and Semantic.

Requires a regenerated OCaml parser  at https://github.com/tree-sitter/tree-sitter-ocaml/pull/37

### CODE REVIEW

**Comment by XVilka** [comment]
Failure is unrelated and caused by C# grammar: https://github.com/tree-sitter/haskell-tree-sitter/issues/284

**Comment by joshvera** [comment]
Looks like a fix is underway at https://github.com/tree-sitter/haskell-tree-sitter/pull/285.

**Comment by XVilka** [comment]
Will be mergeable once https://github.com/tree-sitter/tree-sitter-ocaml/pull/37 is merged.

**Comment by XVilka** [comment]
Now it builds and ready for the review. Please take a look.

**Pull request merged**
