### PR TITLE
Try <> instead of "" for headers found in include-dirs

### PR DESCRIPTION
**Pull request by robrix**
Hopefully this should deal with https://github.com/github/semantic/issues/96.

### CODE REVIEW

**Comment by patrickt** [comment]
Aha, yeah, this is the correct thing. Since they're linked with cabal rather than externally.

**Comment by patrickt** [comment]
Wait hang on. I got confused. This doesn't seem right.

**Comment by patrickt** [comment]
I think we have to do this: install-includes is typically used to name header files that contain prototypes for foreign imports used in Haskell code in this package, for which the C implementations are also provided with the package.

**Comment by robrix** [comment]
The compiler’s getting the `-I` flag (cf #96), which means a system include path (IIRC). I think clang is willing to forgive including files in system include paths with double quotes, and gcc is not?

**Comment by patrickt** [comment]
@robrix I feel like the `-I` flag might be because we're not using an `install-includes` section in the cabal file? These are local files, they should be passed as local includes… right? https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=install%20includes#pkg-field-install-includes

**Comment by patrickt** [comment]
Testing this hypothesis with the `try-using-install-includes` branch failed, but seems to have gotten farther:

```
vendor/tree-sitter/lib/src/lib.c:10:10: error:
     fatal error: './get_changed_ranges.c' file not found
   |
10 | #include "./get_changed_ranges.c"
   |          ^
#include "./get_changed_ranges.c"
```

**Comment by patrickt** [comment]
Wait why is a C file `#include`-ing another C file. what is happening.

**Comment by patrickt** [comment]
Ahh, I see what’s going on. This should be fixed with #129.

Because tree-sitter api.c #includes a whole bunch of C files, we need to ensure that they are all copied into the package appropriately. We had been getting away with this because `stack` aggressively checks out submodules, which were providing these files to gcc.

**Comment by robrix** [comment]
@patrickt: does that mean we can close this out now?

**Comment by robrix** [comment]
Looks like yes.

**Pull request closed without merging**
